[package]
name = "crunch-kv"
version = "0.1.0"
edition = "2021"
publish = ["crates-io"]

[dependencies]
crunch-common.workspace = true
crunch-engine.workspace = true
env_logger.workspace = true
log.workspace = true
tokio.workspace = true
tokio-macros.workspace = true
