[workspace]
members = ["crates/*"]
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
anyhow = "1.0.95"
bloom = "0.2.0"
env_logger = "0.11.6"
log = "0.4.22"
thiserror = "2.0.9"
walkdir = "2.3.2"
