[package]
name = "crunch-kv-client"
version = "0.1.0"
edition = "2021"
publish = ["crates-io"]

[dependencies]
anyhow.workspace = true
clap.workspace = true
env_logger.workspace = true
log.workspace = true
nom.workspace = true
tokio.workspace = true
